[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_limit = 999999999
fs_permissions = [{ access = "read-write", path = "./logs"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
anvil = "http://127.0.0.1:8545" 


[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
anvil = { key = "FAKE KEY", chainId=31337}
